---
# Copies haproxy rpm package from control machine to provisioned machine
- name: Copy rpm to provisioned machine
  copy: src={{ haproxy_rpm }} dest={{ ansible_env.HOME }}

# Installs haproxy from local rpm using yum
- name: Install haproxy
  yum: name={{ ansible_env.HOME }}/{{ haproxy_rpm }} state=present

# Enables haproxy on startup
- name: Enable haproxy on startup
  copy: src=default.cfg dest=/etc/default/haproxy
  notify: reload haproxy

# Copies haproxy configuration files
- name: Configure haproxy instance
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
  notify: reload haproxy

# Start haproxy service
- name: Start haproxy
  service: name=haproxy state=started enabled=yes
